eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: user-service
    api-order:
      path: /api-order/**
      serviceId: order-service